I. Data Cleaning

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('D:/Formation Analyse de données/projet/projet1/afrimarket_dataset_senior.csv')
df.describe()
print(df.head())

  id_commande date_commande id_client        ville     categorie  \
0   CMD100000    2025-12-11     C0379  Brazzaville          Mode
1   CMD100001    2025-07-27     C1827   Libreville        Beauté
2   CMD100002    2025-07-08     C0119      Abidjan  electronique
3   CMD100003    2025-08-20     C1436   Libreville  electronique
4   CMD100004    2025-11-28     C0003   Libreville  Électronique

               nom_produit  prix_unitaire  quantite  remise  cout_livraison  \
0           Produit_Mode_9          49.72         3    0.07            2.45
1         Produit_Beauté_3          37.18         2    0.10            6.89
2  Produit_Électronique_36         315.60         0    0.04            5.60
3  Produit_Électronique_29         143.25         0    0.03            5.96
4  Produit_Électronique_45         498.71         2    0.02            5.16

          methode_paiement canal_marketing  cout_marketing statut_commande
0             Mobile Money           Email            1.00          Livrée
1  Paiement à la livraison   Instagram Ads            8.04          Livrée
2                    Carte      Google Ads            7.30          Livrée
3             Mobile Money      Google Ads            5.20          Livrée
4             Mobile Money           Email            0.55          Livrée

In [3]:
df["date_commande"]=pd.to_datetime(df["date_commande"])

In [4]:
df["date_commande"].dtype

dtype('<M8[us]')

In [5]:
df["date_commande"].dt.strftime("%Y-%m-%d").head()

0    2025-12-11
1    2025-07-27
2    2025-07-08
3    2025-08-20
4    2025-11-28
Name: date_commande, dtype: str

In [6]:
df["date_commande"].dtype

dtype('<M8[us]')

In [ ]:
pd.set_option('display.max_rows', None)
df["categorie"]

0                Mode
1              Beauté
2        electronique
3        electronique
4        Électronique
5              Maison
6                Mode
7              Beauté
8                Mode
9        Électronique
10       Électronique
11       electronique
12               Mode
13               Mode
14       Électronique
15               Mode
16               Mode
17             Maison
18               Mode
19             Maison
20             Maison
21             Maison
22       electronique
23       Électronique
24       Électronique
25             Beauté
26             Maison
27             Beauté
28       electronique
29             Beauté
30             Maison
31             Maison
32             Maison
33               Mode
34       Électronique
35             Beauté
36             Beauté
37               Mode
38             Beauté
39               Mode
40             Maison
41             Beauté
42               Mode
43               Mode
44             Maison
45             Maison
46       Électronique
47       electronique
48             Beauté
49             Maison
50       Électronique
51       electronique
52               Mode
53               Mode
54       Électronique
55       Électronique
56       Électronique
57               Mode
58             Beauté
59               Mode
60       Électronique
61               Mode
62       Électronique
63               Mode
64               Mode
65               Mode
66       Électronique
67               Mode
68               Mode
69       Électronique
70       Électronique
71       Électronique
72             Maison
73       Électronique
74       electronique
75               Mode
76               Mode
77             Beauté
78               Mode
79       electronique
80               Mode
81               Mode
82             Maison
83             Maison
84               Mode
85               Mode
86       electronique
87       Électronique
88               Mode
89               Mode
90             Maison
91             Beauté
92               Mode
93       Électronique
94       Électronique
95             Maison
96             Maison
97       Électronique
98               Mode
99             Maison
100              Mode
101              Mode
102            Beauté
103      Électronique
104              Mode
105      electronique
106      Électronique
107              Mode
108            Beauté
109              Mode
110      Électronique
111            Beauté
112            Maison
113              Mode
114      Électronique
115              Mode
116      electronique
117      Électronique
118            Beauté
119            Beauté
120            Maison
121              Mode
122            Beauté
123              Mode
124      electronique
125              Mode
126              Mode
127            Beauté
128              Mode
129      Électronique
130            Beauté
131            Beauté
132            Beauté
133            Maison
134            Beauté
135              Mode
136            Beauté
137      Électronique
138      Électronique
139      Électronique
140              Mode
141              Mode
142            Beauté
143            Beauté
144              Mode
145            Beauté
146      Électronique
147              Mode
148              Mode
149            Maison
150      Électronique
151            Maison
152              Mode
153            Beauté
154            Maison
155              Mode
156              Mode
157              Mode
158              Mode
159      Électronique
160      Électronique
161              Mode
162      Électronique
163      electronique
164      Électronique
165      electronique
166      Électronique
167            Maison
168              Mode
169              Mode
170      Électronique
171              Mode
172              Mode
173              Mode
174            Beauté
175            Beauté
176      Électronique
177            Maison
178      Électronique
179            Maison
180            Beauté
181            Maison
182              Mode
183      Électronique
184      Électronique
185            Maison
186            Maison
187            Beauté
188            Maison
189            Maison
190              Mode
191              Mode
192            Beauté
193      electronique
194            Maison
195            Beauté
196      electronique
197            Beauté
198      electronique
199      Électronique
200            Maison
201      Électronique
202            Maison
203      Électronique
204            Maison
205      electronique
206            Beauté
207      Électronique
208              Mode
209      Électronique
210      Électronique
211      Électronique
212            Beauté
213              Mode
214              Mode
215      Électronique
216            Beauté
217            Maison
218      electronique
219      Électronique
220      Électronique
221      Électronique
222            Beauté
223              Mode
224              Mode
225      Électronique
226      Électronique
227              Mode
228            Maison
229            Beauté
230            Beauté
231              Mode
232              Mode
233      Électronique
234            Maison
235              Mode
236              Mode
237            Maison
238            Maison
239      Électronique
240            Beauté
241            Maison
242            Beauté
243      Électronique
244      Électronique
245            Maison
246      Électronique
247            Beauté
248            Maison
249            Maison
250              Mode
251            Maison
252      Électronique
253      Électronique
254            Maison
255            Beauté
256            Beauté
257      Électronique
258            Maison
259            Beauté
260      Électronique
261              Mode
262      Électronique
263            Maison
264              Mode
265            Beauté
266              Mode
267              Mode
268              Mode
269            Maison
270      Électronique
271      Électronique
272            Maison
273            Beauté
274            Maison
275            Beauté
276            Beauté
277              Mode
278              Mode
279              Mode
280            Beauté
281      Électronique
282      Électronique
283              Mode
284      Électronique
285            Maison
286      Électronique
287              Mode
288              Mode
289            Beauté
290            Beauté
291      Électronique
292            Maison
293            Maison
294              Mode
295            Beauté
296            Beauté
297      Électronique
298            Beauté
299            Beauté
300            Maison
301              Mode
302      Électronique
303            Beauté
304              Mode
305      Électronique
306            Beauté
307      Électronique
308            Maison
309      electronique
310            Maison
311              Mode
312            Beauté
313              Mode
314              Mode
315              Mode
316      Électronique
317              Mode
318            Maison
319      Électronique
320            Maison
321            Beauté
322            Beauté
323              Mode
324            Maison
325            Beauté
326      electronique
327            Beauté
328      Électronique
329            Maison
330      electronique
331              Mode
332            Beauté
333              Mode
334            Maison
335            Beauté
336              Mode
337            Beauté
338      electronique
339            Maison
340              Mode
341            Beauté
342            Beauté
343            Maison
344            Beauté
345      Électronique
346            Beauté
347      Électronique
348      electronique
349      Électronique
350            Beauté
351      Électronique
352              Mode
353      Électronique
354      Électronique
355            Beauté
356              Mode
357            Beauté
358              Mode
359              Mode
360      Électronique
361      Électronique
362      Électronique
363      Électronique
364            Beauté
365      Électronique
366            Beauté
367            Beauté
368            Beauté
369              Mode
370      electronique
371      Électronique
372      electronique
373            Maison
374            Beauté
375              Mode
376            Beauté
377              Mode
378      Électronique
379              Mode
380              Mode
381      Électronique
382      Électronique
383            Beauté
384              Mode
385              Mode
386            Beauté
387              Mode
388            Beauté
389            Beauté
390              Mode
391              Mode
392            Maison
393            Beauté
394            Beauté
395      Électronique
396              Mode
397              Mode
398            Beauté
399              Mode
400              Mode
401      electronique
402            Maison
403              Mode
404      Électronique
405              Mode
406              Mode
407            Beauté
408              Mode
409              Mode
410              Mode
411      Électronique
412      electronique
413            Beauté
414      electronique
415      electronique
416            Beauté
417            Maison
418              Mode
419              Mode
420      Électronique
421            Maison
422      electronique
423      Électronique
424            Maison
425              Mode
426            Maison
427            Maison
428            Maison
429      Électronique
430            Beauté
431              Mode
432            Beauté
433      Électronique
434            Maison
435            Maison
436            Maison
437              Mode
438            Maison
439            Maison
440            Maison
441            Beauté
442            Maison
443              Mode
444            Beauté
445      Électronique
446              Mode
447      Électronique
448              Mode
449            Maison
450            Maison
451            Maison
452      Électronique
453              Mode
454            Beauté
455      Électronique
456              Mode
457            Maison
458            Beauté
459            Beauté
460              Mode
461            Beauté
462            Beauté
463              Mode
464              Mode
465              Mode
466              Mode
467            Maison
468      Électronique
469      electronique
470              Mode
471              Mode
472              Mode
473      Électronique
474            Beauté
475              Mode
476              Mode
477      Électronique
478            Maison
479              Mode
480      electronique
481            Maison
482            Beauté
483            Maison
484      Électronique
485              Mode
486            Beauté
487      Électronique
488              Mode
489              Mode
490      electronique
491              Mode
492            Beauté
493            Maison
494            Beauté
495      Électronique
496      electronique
497      electronique
498      Électronique
499              Mode
500      electronique
501      electronique
502              Mode
503      Électronique
504      Électronique
505              Mode
506              Mode
507            Beauté
508            Maison
509            Maison
510            Maison
511      Électronique
512              Mode
513            Maison
514              Mode
515              Mode
516      Électronique
517            Beauté
518              Mode
519      Électronique
520            Maison
521              Mode
522            Maison
523              Mode
524            Maison
525            Beauté
526      Électronique
527              Mode
528            Beauté
529              Mode
530            Maison
531              Mode
532            Maison
533              Mode
534      Électronique
535            Maison
536              Mode
537              Mode
538            Maison
539      Électronique
540              Mode
541              Mode
542      Électronique
543            Maison
544      electronique
545      Électronique
546            Maison
547      Électronique
548      electronique
549              Mode
550            Beauté
551            Maison
552            Maison
553      Électronique
554              Mode
555            Maison
556              Mode
557            Maison
558      Électronique
559      Électronique
560            Maison
561            Beauté
562            Beauté
563      Électronique
564            Maison
565              Mode
566      electronique
567      Électronique
568            Maison
569              Mode
570            Maison
571            Maison
572      Électronique
573      Électronique
574            Maison
575              Mode
576            Beauté
577              Mode
578              Mode
579      Électronique
580      electronique
581      Électronique
582              Mode
583      Électronique
584            Beauté
585              Mode
586            Maison
587      Électronique
588            Maison
589      Électronique
590      Électronique
591      Électronique
592      Électronique
593            Beauté
594              Mode
595            Maison
596            Beauté
597              Mode
598              Mode
599      electronique
600      Électronique
601      Électronique
602      Électronique
603      Électronique
604      Électronique
605            Maison
606              Mode
607            Beauté
608              Mode
609      Électronique
610              Mode
611            Maison
612            Maison
613            Beauté
614              Mode
615              Mode
616      Électronique
617              Mode
618            Maison
619      Électronique
620      Électronique
621              Mode
622      Électronique
623              Mode
624            Beauté
625            Beauté
626              Mode
627              Mode
628              Mode
629            Maison
630            Maison
631            Maison
632            Maison
633      Électronique
634            Maison
635              Mode
636              Mode
637              Mode
638            Beauté
639            Maison
640      Électronique
641              Mode
642      Électronique
643            Beauté
644            Beauté
645              Mode
646              Mode
647              Mode
648      electronique
649      Électronique
650              Mode
651      Électronique
652            Beauté
653              Mode
654            Beauté
655      Électronique
656      Électronique
657            Beauté
658              Mode
659            Maison
660            Maison
661              Mode
662      Électronique
663            Beauté
664      electronique
665            Maison
666      electronique
667            Beauté
668            Maison
669              Mode
670              Mode
671            Maison
672            Maison
673              Mode
674              Mode
675              Mode
676            Maison
677              Mode
678              Mode
679            Maison
680              Mode
681      Électronique
682            Beauté
683      Électronique
684            Maison
685              Mode
686            Maison
687            Beauté
688      Électronique
689            Beauté
690      Électronique
691            Maison
692            Maison
693              Mode
694      Électronique
695            Beauté
696              Mode
697              Mode
698            Maison
699              Mode
700            Maison
701      Électronique
702            Maison
703            Maison
704      electronique
705            Maison
706            Beauté
707            Maison
708              Mode
709            Beauté
710            Maison
711              Mode
712              Mode
713      Électronique
714      Électronique
715            Beauté
716      Électronique
717              Mode
718              Mode
719              Mode
720      Électronique
721              Mode
722            Maison
723              Mode
724      Électronique
725            Maison
726      Électronique
727              Mode
728            Beauté
729      Électronique
730              Mode
731            Maison
732            Beauté
733            Beauté
734      Électronique
735              Mode
736              Mode
737            Maison
738            Maison
739            Maison
740            Beauté
741              Mode
742            Beauté
743      Électronique
744      Électronique
745      Électronique
746              Mode
747            Beauté
748            Maison
749      electronique
750      Électronique
751              Mode
752            Beauté
753      Électronique
754            Beauté
755            Beauté
756            Maison
757      electronique
758      Électronique
759            Beauté
760      Électronique
761      Électronique
762            Maison
763            Maison
764              Mode
765            Maison
766              Mode
767            Beauté
768            Maison
769      Électronique
770            Maison
771      Électronique
772              Mode
773      Électronique
774            Beauté
775      Électronique
776              Mode
777              Mode
778            Beauté
779            Beauté
780              Mode
781              Mode
782              Mode
783              Mode
784            Maison
785              Mode
786              Mode
787            Maison
788            Maison
789            Beauté
790      Électronique
791      Électronique
792      electronique
793      Électronique
794              Mode
795              Mode
796      Électronique
797            Maison
798      Électronique
799              Mode
800      Électronique
801            Maison
802      Électronique
803              Mode
804              Mode
805            Beauté
806      Électronique
807              Mode
808              Mode
809              Mode
810              Mode
811              Mode
812      Électronique
813            Beauté
814      Électronique
815      Électronique
816            Beauté
817            Maison
818            Beauté
819              Mode
820              Mode
821      Électronique
822              Mode
823            Maison
824              Mode
825              Mode
826            Beauté
827            Beauté
828      electronique
829      electronique
830            Beauté
831              Mode
832              Mode
833            Maison
834      Électronique
835            Beauté
836      Électronique
837            Beauté
838              Mode
839      Électronique
840            Beauté
841              Mode
842              Mode
843              Mode
844              Mode
845            Beauté
846            Beauté
847              Mode
848              Mode
849            Beauté
850            Beauté
851            Beauté
852            Maison
853              Mode
854              Mode
855            Maison
856            Beauté
857            Beauté
858      Électronique
859            Beauté
860      Électronique
861            Beauté
862            Maison
863      Électronique
864      Électronique
865              Mode
866            Beauté
867      Électronique
868              Mode
869            Maison
870              Mode
871            Maison
872              Mode
873      Électronique
874              Mode
875              Mode
876            Beauté
877            Beauté
878              Mode
879              Mode
880              Mode
881            Beauté
882            Beauté
883              Mode
884              Mode
885            Maison
886              Mode
887            Maison
888              Mode
889              Mode
890      Électronique
891            Maison
892              Mode
893            Maison
894            Beauté
895            Beauté
896            Maison
897              Mode
898              Mode
899              Mode
900            Maison
901            Beauté
902            Maison
903      electronique
904            Beauté
905            Beauté
906            Beauté
907              Mode
908            Maison

In [7]:
df["categorie"].unique()

<StringArray>
['Mode', 'Beauté', 'electronique', 'Électronique', 'Maison']
Length: 5, dtype: str

méthode ULTRA PRO que les Data Analysts utilisent pour détecter automatiquement des catégories non uniformisées
Détecter les variantes cachées (méthode entreprise)

👉 On compare :

version originale

version normalisée

In [12]:
df["categorie_clean_test"]=(df["categorie"].str.lower().str.normalize("NFKD").str.encode("ascii", errors="ignore").str.decode("utf-8"))

2️⃣ Voir les différences entre les deux

In [13]:
df[["categorie","categorie_clean_test"]].drop_duplicates()

      categorie categorie_clean_test
0          Mode                 mode
1        Beaute               beaute
2  Electronique         electronique
5        Maison               maison

3️⃣ Détection automatique des catégories suspectes

In [14]:
df.groupby("categorie_clean_test")["categorie"].unique()

categorie_clean_test
beaute                [Beaute]
electronique    [Electronique]
maison                [Maison]
mode                    [Mode]
Name: categorie, dtype: object

4️⃣ Ensuite tu peux corriger définitivement

In [24]:
df[["categorie","categorie_clean_test"]].head()

      categorie categorie_clean_test
0          Mode                 mode
1        Beaute               beaute
2  Electronique         electronique
3  Electronique         electronique
4  Electronique         electronique

In [25]:
df["categorie"]=df["categorie_clean_test"].str.capitalize()

In [26]:
df.drop(columns="categorie_clean_test", inplace=True)

●	Corriger les villes mal orthographiées

In [19]:
df["ville"].unique()

<StringArray>
['Brazzaville',  'Libreville',     'Abidjan',       'Dakar',        'Lomé',
     'Cotonou',    'Kinshasa',      'Douala',   'Kinshassa']
Length: 9, dtype: str

villes ne sont pas uniformisées non plus.

Je vois immédiatement un problème :

Kinshasa
Kinshassa   ❌ (faute d’orthographe)
Pour Python ce sont deux villes différentes.

In [27]:
df["ville"].value_counts()

ville
Kinshasa       2349
Abidjan        1886
Douala         1449
Dakar          1434
Lomé            735
Cotonou         677
Kinshassa       605
Libreville      493
Brazzaville     472
Name: count, dtype: int64

In [30]:
df["ville"]=df["ville"].replace({"Kinshassa":"Kinshasa" })

In [31]:
df["ville"].unique()

<StringArray>
['Brazzaville',  'Libreville',     'Abidjan',       'Dakar',        'Lomé',
     'Cotonou',    'Kinshasa',      'Douala']
Length: 8, dtype: str

In [32]:
df["remise"]

0        0.07
1        0.10
2        0.04
3        0.03
4        0.02
         ...
10095    0.10
10096    0.12
10097   -0.10
10098    0.20
10099    0.30
Name: remise, Length: 10100, dtype: float64

Gérer les remises négatives” veut dire :
traiter les cas où la colonne remise contient des valeurs < 0 (ce qui est souvent une anomalie dans les données).

In [34]:
df[df["remise"]<0]

,id_commande,date_commande,id_client,ville,categorie,nom_produit,prix_unitaire,quantite,remise,cout_livraison,methode_paiement,canal_marketing,cout_marketing,statut_commande
6,CMD100006,2025-07-24,C0183,Abidjan,Mode,Produit_Mode_3,23.04,3,-0.1,3.59,Virement,Instagram Ads,9.23,Livrée
23,CMD100023,2025-09-06,C1560,Kinshasa,Electronique,Produit_Électronique_41,370.82,3,-0.1,2.56,Carte,Instagram Ads,8.73,Livrée
33,CMD100033,2025-07-09,C0145,Dakar,Mode,Produit_Mode_43,41.26,1,-0.1,4.19,Virement,Google Ads,6.26,Livrée
38,CMD100038,2025-08-18,C0071,Douala,Beaute,Produit_Beauté_5,18.17,1,-0.1,2.73,Mobile Money,Instagram Ads,11.73,Livrée
54,CMD100054,2025-11-19,C0339,Kinshasa,Electronique,Produit_Électronique_17,443.99,1,-0.1,3.35,Mobile Money,Influenceur,4.65,retournée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10068,CMD100201,2025-11-16,C0089,Dakar,Electronique,Produit_Électronique_9,-50.00,2,-0.1,8.72,Carte,Influenceur,15.19,retournée
10071,CMD107405,2025-07-19,C0141,Abidjan,Maison,Produit_Maison_37,83.82,2,-0.1,4.16,Mobile Money,Google Ads,7.04,Livrée
10077,CMD101496,2025-08-20,C0512,Douala,Electronique,Produit_Électronique_13,339.74,2,-0.1,5.43,Virement,Instagram Ads,5.25,Livrée
10083,CMD109681,2025-10-04,C0356,Kinshasa,Maison,Produit_Maison_37,139.00,2,-0.1,7.06,Paiement à la livraison,Instagram Ads,10.49,Livrée
10097,CMD107567,2025-11-22,C0099,Kinshasa,Electronique,Produit_Maison_42,90.60,0,-0.1,5.53,Paiement à la livraison,Google Ads,4.55,Livrée

In [35]:
(df["remise"]<0).sum()

np.int64(614)

méthode A: remplaer par 0
df.loc[ ... , ... ]

👉 .loc sert à sélectionner des lignes et des colonnes.

Structure :

df.loc[lignes, colonnes]
Dans ton cas :

lignes = df["remise"] < 0
colonnes = "remise"


Donc :

👉 sélectionne uniquement les lignes où la remise est négative, dans la colonne remise.
= 0

👉 Remplace les valeurs sélectionnées par 0.

In [36]:
df.loc[df["remise"]<0,"remise"]=0

In [37]:
(df["remise"]<0).sum()

np.int64(0)

●	Gérer les prix aberrants
détecter et traiter les prix qui semblent anormaux dans ton dataset.

Un prix aberrant = un prix qui sort du comportement normal.

In [38]:
df["prix_unitaire"].describe()

count    10100.000000
mean       140.493353
std        172.031607
min        -50.000000
25%         28.057500
50%         52.975000
75%        201.885000
max        915.860000
Name: prix_unitaire, dtype: float64

Prix négatifs détectés :-50
Prix très élevés (potentiels outliers) : 915.860000
Mais la médiane est seulement :52.97
👉 Ça veut dire qu’il y a des valeurs très éloignées de la majorité.
3️⃣ Méthode PRO — Calculer les limites IQR
Tout ce qui dépasse ~462 est probablement aberrant.

In [42]:
Q1=df["prix_unitaire"].quantile(0.25)
Q3=df["prix_unitaire"].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print(lower_bound, upper_bound )
outliers=df[(df["prix_unitaire"]<lower_bound) | (df["prix_unitaire"]>upper_bound)]
print(outliers)

-232.68374999999997 462.62624999999997
      id_commande date_commande id_client        ville     categorie  \
4       CMD100004    2025-11-28     C0003   Libreville  Electronique
9       CMD100009    2025-12-17     C0148        Dakar  Electronique
11      CMD100011    2025-09-29     C0136      Cotonou  Electronique
14      CMD100014    2025-09-22     C1589      Abidjan  Electronique
60      CMD100060    2025-07-10     C1192      Abidjan  Electronique
...           ...           ...       ...          ...           ...
10018   CMD103281    2025-07-01     C0354     Kinshasa  Electronique
10026   CMD106712    2025-12-23     C0126       Douala  Electronique
10053   CMD102428    2025-08-19     C1255  Brazzaville  Electronique
10073   CMD103755    2025-11-21     C0069      Abidjan  Electronique
10089   CMD107864    2025-10-09     C0077     Kinshasa  Electronique

                   nom_produit  prix_unitaire  quantite  remise  \
4      Produit_Électronique_45         498.71         2    0.02
9       Produit_Électronique_7         562.75         2    0.08
11     Produit_Électronique_39         489.25         3    0.08
14     Produit_Électronique_21         572.02         1    0.10
60      Produit_Électronique_9         567.49         2    0.17
...                        ...            ...       ...     ...
10018  Produit_Électronique_28         612.54         1    0.24
10026  Produit_Électronique_37         479.27         1    0.07
10053  Produit_Électronique_43         868.34         1    0.28
10073   Produit_Électronique_1         520.10         0    0.29
10089  Produit_Électronique_21         520.10         2    0.08

       cout_livraison         methode_paiement canal_marketing  \
4                5.16             Mobile Money           Email
9                9.26             Mobile Money   Instagram Ads
11               2.00                    Carte   Instagram Ads
14               7.83                    Carte           Email
60               4.92  Paiement à la livraison   Instagram Ads
...               ...                      ...             ...
10018            8.90  Paiement à la livraison   Instagram Ads
10026            2.10                    Carte           Email
10053            9.30  Paiement à la livraison   Instagram Ads
10073            4.08             Mobile Money   Instagram Ads
10089            8.21                    Carte     Influenceur

       cout_marketing statut_commande
4                0.55          Livrée
9                5.31          Livrée
11               8.56          Livrée
14               1.51       retournée
60               8.30          Livrée
...               ...             ...
10018           10.14          Livrée
10026            1.92          Livrée
10053            7.30          Livrée
10073            7.66          Livrée
10089           10.03       retournée

[799 rows x 14 columns]

In [43]:
df["prix_unitaire"]=df["prix_unitaire"].clip(lower=0, upper=upper_bound)

In [44]:
df["prix_unitaire"].describe()

count    10100.000000
mean       137.415476
std        154.374639
min          0.000000
25%         28.057500
50%         52.975000
75%        201.885000
max        462.626250
Name: prix_unitaire, dtype: float64

●	Supprimer ou traiter les quantités nulles

In [45]:
df["quantite"].describe()

count    10100.000000
mean         1.866040
std          0.920966
min          0.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: quantite, dtype: float64

In [46]:
(df["quantite"]==0).sum()

np.int64(608)

In [47]:
df[df["quantite"]==0]

,id_commande,date_commande,id_client,ville,categorie,nom_produit,prix_unitaire,quantite,remise,cout_livraison,methode_paiement,canal_marketing,cout_marketing,statut_commande
2,CMD100002,2025-07-08,C0119,Abidjan,Electronique,Produit_Électronique_36,315.60000,0,0.04,5.60,Carte,Google Ads,7.30,Livrée
3,CMD100003,2025-08-20,C1436,Libreville,Electronique,Produit_Électronique_29,143.25000,0,0.03,5.96,Mobile Money,Google Ads,5.20,Livrée
35,CMD100035,2025-10-30,C0389,Dakar,Beaute,Produit_Beauté_23,21.56000,0,0.15,6.61,Paiement à la livraison,Instagram Ads,14.68,Livrée
45,CMD100045,2025-09-19,C0299,Brazzaville,Maison,Produit_Maison_4,122.17000,0,0.06,6.67,Mobile Money,Email,0.78,Livrée
46,CMD100046,2025-11-08,C0095,Brazzaville,Electronique,Produit_Électronique_44,170.48000,0,0.02,6.91,Carte,Google Ads,7.75,retournée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10073,CMD103755,2025-11-21,C0069,Abidjan,Electronique,Produit_Électronique_1,462.62625,0,0.29,4.08,Mobile Money,Instagram Ads,7.66,Livrée
10076,CMD100304,2025-09-20,C1453,Kinshasa,Mode,Produit_Mode_20,49.59000,0,0.27,7.73,Virement,Google Ads,3.78,retournée
10088,CMD107474,2025-08-03,C1480,Kinshasa,Beaute,Produit_Beauté_36,26.14000,0,0.18,9.00,Paiement à la livraison,Instagram Ads,6.41,Livrée
10096,CMD108770,2025-12-27,C0009,Kinshasa,Mode,Produit_Mode_37,21.12000,0,0.12,8.91,Virement,Instagram Ads,10.46,Livrée
10097,CMD107567,2025-11-22,C0099,Kinshasa,Electronique,Produit_Maison_42,90.60000,0,0.00,5.53,Paiement à la livraison,Google Ads,4.55,Livrée

In [ ]:
Supprimer les quantités nulles (le plus courant)

In [48]:
df=df[df["quantite"]>0]

In [49]:
(df["quantite"]==0).sum()

np.int64(0)

●	Gérer les doublons
Un doublon = deux lignes (ou plus) identiques.
Étape 1 — Détecter les doublons

In [50]:
df.duplicated().sum()

np.int64(92)

Afficher les doublons

In [51]:
df[df.duplicated() ]

,id_commande,date_commande,id_client,ville,categorie,nom_produit,prix_unitaire,quantite,remise,cout_livraison,methode_paiement,canal_marketing,cout_marketing,statut_commande
10000,CMD102576,2025-07-31,C0924,Kinshasa,Mode,Produit_Mode_14,13.63,1,0.24,7.42,Paiement à la livraison,Google Ads,7.62,retournée
10001,CMD102940,2025-09-24,C0039,Brazzaville,Mode,Produit_Mode_45,44.07,1,0.10,9.77,Carte,Google Ads,7.80,Livrée
10002,CMD107540,2025-09-21,C1880,Abidjan,Electronique,Produit_Électronique_14,0.00,1,0.04,7.34,Mobile Money,Google Ads,4.76,Livrée
10003,CMD104223,2025-12-12,C1305,Cotonou,Mode,Produit_Mode_28,32.56,2,0.26,8.42,Paiement à la livraison,Instagram Ads,8.40,Livrée
10005,CMD103856,2025-09-15,C0012,Abidjan,Beaute,Produit_Beauté_22,8.94,1,0.21,5.35,Carte,Instagram Ads,5.50,Livrée
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10093,CMD104687,2025-10-17,C0394,Kinshasa,Mode,Produit_Mode_35,0.00,3,0.20,5.96,Mobile Money,Email,0.70,Livrée
10094,CMD101287,2025-10-27,C0359,Douala,Electronique,Produit_Électronique_39,239.26,3,0.10,4.32,Paiement à la livraison,Email,1.84,retournée
10095,CMD104520,2025-10-07,C0176,Brazzaville,Beaute,Produit_Beauté_44,24.82,1,0.10,3.75,Carte,Instagram Ads,8.06,Livrée
10098,CMD109850,2025-09-22,C0292,Abidjan,Beaute,Produit_Beauté_48,29.13,1,0.20,9.47,Paiement à la livraison,Instagram Ads,9.88,Livrée
10099,CMD100945,2025-08-07,C1156,Kinshasa,Mode,Produit_Mode_5,34.34,3,0.30,9.75,Virement,Influenceur,15.83,Livrée

Étape 2 — Vérifier selon certaines colonnes

In [53]:
df=df.drop_duplicates()

In [55]:
df.shape

(9400, 14)

In [56]:
df[df.duplicated() ]

Empty DataFrame
Columns: [id_commande, date_commande, id_client, ville, categorie, nom_produit, prix_unitaire, quantite, remise, cout_livraison, methode_paiement, canal_marketing, cout_marketing, statut_commande]
Index: []

Les doublons ont été supprimés afin d’éviter une surreprésentation
de certaines transactions dans l’analyse.

👉 “Uniformiser les statuts” veut dire :

rendre toutes les valeurs de la colonne statut cohérentes et identiques pour éviter les variantes.

In [61]:
df["statut_commande"].unique()

<StringArray>
['Livrée', 'retournée', 'Annulée']
Length: 3, dtype: str

In [62]:
df["statut_commande"].value_counts(dropna=False )

statut_commande
Livrée       8452
retournée     765
Annulée       183
Name: count, dtype: int64

✅ Tes statuts sont déjà presque uniformisés (il n’y a que 3 valeurs).

Le seul “petit problème” visible : la casse (ex: retournée est en minuscule alors que les autres commencent par une majuscule).

In [63]:
df["statut_commande"]=df["statut_commande"].str.strip().str.capitalize()

In [64]:
df["statut_commande"].unique()

<StringArray>
['Livrée', 'Retournée', 'Annulée']
Length: 3, dtype: str

In [65]:
df_clean=df

In [ ]:
df_clean

NameError: name 'df_clean' is not defined